defaults:
  - env: minigrid
  - learning: ippo-minigrid-ncc
  - ued: ncc
  - _self_

"SEED": 2
"GROUP_NAME": "minigrid-ncc"
"ENTITY": ""
"PROJECT": "minigrid"
"WANDB_MODE" : "online"
"SAVE_PATH": "checkpoints/new_minigrid"
"CHECKPOINT_SAVE_INTERVAL": 0
"META_LR": 0.005
"META_REG": 0.032
"META_TRUNC": 1e-5